version: '3'
services:
  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=baked_cakes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./docker/mysql/default_authentication.cnf:/etc/mysql/conf.d/default_authentication.cnf
      - ./docker/misc/data:/var/lib/mysql
    ports:
      - "33306:3306"

  web:
    container_name: web
    build: ./docker/nginx
    restart: always
    links:
      - app
    ports:
      - "4443:443"
    volumes:
      - .:/var/www/html

  app:
    container_name: app
    build: ./docker/php
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    links:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: baked_cakes
      DATABASE_USER: user
      DATABASE_PASSWORD: password
